server:
  port: 8000
spring:
  application:
    name: mytennis
  datasource:
    url: jdbc:postgresql://localhost:5432/mytenis?serverTimeZone=ADT
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring-doc:
  api-docs:
    path: /api-docs
    pathsToMatch: /api/**
    swagger-ui:
      use-root-path: true